version: '3'
services:
  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379

    labels:
      - 'name=redis'
      - 'mode=standalone'

    restart: 'no'
    command: redis-server

    networks:
      - node-network

  api:
    depends_on:
      - redis_server

    build:
      context: .
      dockerfile: Dockerfile-local

    environment:
      NODE_ENV: development
      PORT: 8080
      REDIS_HOST: redis_server
      REDIS_PORT: 6379

    ports:
      - 8080:8080

    networks:
      - node-network

networks:
  node-network:
